FROM golang:1.15

RUN apt-get update -qq
RUN apt-get install -y -qq libtesseract-dev libleptonica-dev
ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata/
RUN apt-get install -y -qq tesseract-ocr-eng

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

ENV SOCR_LISTEN_ADDR :80
ENV SOCR_SCREENSHOTS_PATH /screenshots
ENV SOCR_FRONTEND_DIR /frontend
ENV SOCR_INDEX_PATH /index

CMD ["go", "run", "cmd/socr/main.go"]
