FROM golang:1.16
WORKDIR /src

RUN apt-get update -qq
RUN apt-get install -y -qq libtesseract-dev libleptonica-dev ffmpeg build-essential libavcodec-dev libavutil-dev libavformat-dev libswscale-dev libgraphicsmagick1-dev
ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata/
RUN apt-get install -y -qq tesseract-ocr-eng
