#!/usr/bin/env bash

pggen gen go \
    --schema-glob db/schema.pgsql \
    --query-glob db/queries.pgsql \
    --output-dir db \
    --go-type "timestamptz=time.Time" \
    --go-type "text=string" \
    --go-type "smallint=int" \
    --go-type "integer=int" \
    --go-type "bigint=int" \
    --go-type "decimal=float64" \
    --go-type "double precision=float64" \
    --postgres-connection "host=localhost user=socr password=socr port=5444 dbname=socr"
