// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"fmt"
	"time"
)

type Filetype string

const (
	FiletypeGIF Filetype = "GIF"
	FiletypePNG Filetype = "PNG"
	FiletypeJPG Filetype = "JPG"
)

func (e *Filetype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Filetype(s)
	case string:
		*e = Filetype(s)
	default:
		return fmt.Errorf("unsupported scan type for Filetype: %T", src)
	}
	return nil
}

type Block struct {
	ID           int32  `json:"id"`
	ScreenshotID int64  `json:"screenshot_id"`
	Index        int16  `json:"index"`
	MinX         int16  `json:"min_x"`
	MinY         int16  `json:"min_y"`
	MaxX         int16  `json:"max_x"`
	MaxY         int16  `json:"max_y"`
	Body         string `json:"body"`
}

type Screenshot struct {
	ID             int64     `json:"id"`
	Timestamp      time.Time `json:"timestamp"`
	DirectoryAlias string    `json:"directory_alias"`
	Filename       string    `json:"filename"`
	Filetype       Filetype  `json:"filetype"`
	DimWidth       int32     `json:"dim_width"`
	DimHeight      int32     `json:"dim_height"`
	DominantColour string    `json:"dominant_colour"`
	Blurhash       string    `json:"blurhash"`
}

type Tag struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type TagScreenshot struct {
	TagID        int64 `json:"tag_id"`
	ScreenshotID int64 `json:"screenshot_id"`
}
