// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Block struct {
	ID           int32
	ScreenshotID int64
	Index        int16
	MinX         int16
	MinY         int16
	MaxX         int16
	MaxY         int16
	Body         string
}

type Screenshot struct {
	ID             int64
	Timestamp      time.Time
	DirectoryAlias string
	Filename       string
	DimWidth       int32
	DimHeight      int32
	DominantColour string
	Blurhash       string
}

type Tag struct {
	ID   int32
	Name string
}

type TagScreenshot struct {
	TagID        int64
	ScreenshotID int64
}
