// Code generated by sqlc. DO NOT EDIT.
// source: queries.pgsql

package db

import (
	"context"
	"time"

	"go.senan.xyz/socr/backend/hasher"
)

const countDirectoriesByAlias = `-- name: CountDirectoriesByAlias :many
select
    directory_alias,
    count(1)
from
    screenshots
group by
    directory_alias
`

type CountDirectoriesByAliasRow struct {
	DirectoryAlias string `json:"directory_alias"`
	Count          int64  `json:"count"`
}

func (q *Queries) CountDirectoriesByAlias(ctx context.Context) ([]CountDirectoriesByAliasRow, error) {
	rows, err := q.query(ctx, q.countDirectoriesByAliasStmt, countDirectoriesByAlias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDirectoriesByAliasRow
	for rows.Next() {
		var i CountDirectoriesByAliasRow
		if err := rows.Scan(&i.DirectoryAlias, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBlock = `-- name: CreateBlock :exec
insert into blocks (screenshot_id, index, min_x, min_y, max_x, max_y, body)
        values ($1, $2, $3, $4, $5, $6, $7)
`

type CreateBlockParams struct {
	ScreenshotID hasher.ID `json:"screenshot_id"`
	Index        int16     `json:"index"`
	MinX         int16     `json:"min_x"`
	MinY         int16     `json:"min_y"`
	MaxX         int16     `json:"max_x"`
	MaxY         int16     `json:"max_y"`
	Body         string    `json:"body"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.exec(ctx, q.createBlockStmt, createBlock,
		arg.ScreenshotID,
		arg.Index,
		arg.MinX,
		arg.MinY,
		arg.MaxX,
		arg.MaxY,
		arg.Body,
	)
	return err
}

const createScreenshot = `-- name: CreateScreenshot :one
insert into screenshots (id, timestamp, directory_alias, filename, dim_width, dim_height, dominant_colour, blurhash)
    values ($1, $2, $3, $4, $5, $6, $7, $8)
returning
    id, timestamp, directory_alias, filename, dim_width, dim_height, dominant_colour, blurhash
`

type CreateScreenshotParams struct {
	ID             hasher.ID `json:"id"`
	Timestamp      time.Time `json:"timestamp"`
	DirectoryAlias string    `json:"directory_alias"`
	Filename       string    `json:"filename"`
	DimWidth       int32     `json:"dim_width"`
	DimHeight      int32     `json:"dim_height"`
	DominantColour string    `json:"dominant_colour"`
	Blurhash       string    `json:"blurhash"`
}

func (q *Queries) CreateScreenshot(ctx context.Context, arg CreateScreenshotParams) (Screenshot, error) {
	row := q.queryRow(ctx, q.createScreenshotStmt, createScreenshot,
		arg.ID,
		arg.Timestamp,
		arg.DirectoryAlias,
		arg.Filename,
		arg.DimWidth,
		arg.DimHeight,
		arg.DominantColour,
		arg.Blurhash,
	)
	var i Screenshot
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.DirectoryAlias,
		&i.Filename,
		&i.DimWidth,
		&i.DimHeight,
		&i.DominantColour,
		&i.Blurhash,
	)
	return i, err
}

const getAllScreenshots = `-- name: GetAllScreenshots :many
select
    id, timestamp, directory_alias, filename, dim_width, dim_height, dominant_colour, blurhash
from
    screenshots
`

func (q *Queries) GetAllScreenshots(ctx context.Context) ([]Screenshot, error) {
	rows, err := q.query(ctx, q.getAllScreenshotsStmt, getAllScreenshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screenshot
	for rows.Next() {
		var i Screenshot
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.DirectoryAlias,
			&i.Filename,
			&i.DimWidth,
			&i.DimHeight,
			&i.DominantColour,
			&i.Blurhash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScreenshotByID = `-- name: GetScreenshotByID :one
select
    id, timestamp, directory_alias, filename, dim_width, dim_height, dominant_colour, blurhash
from
    screenshots
where
    id = $1
limit 1
`

func (q *Queries) GetScreenshotByID(ctx context.Context, id hasher.ID) (Screenshot, error) {
	row := q.queryRow(ctx, q.getScreenshotByIDStmt, getScreenshotByID, id)
	var i Screenshot
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.DirectoryAlias,
		&i.Filename,
		&i.DimWidth,
		&i.DimHeight,
		&i.DominantColour,
		&i.Blurhash,
	)
	return i, err
}

const getScreenshotByPath = `-- name: GetScreenshotByPath :one
select
    id, timestamp, directory_alias, filename, dim_width, dim_height, dominant_colour, blurhash
from
    screenshots
where
    directory_alias = $1
    and filename = $2
limit 1
`

type GetScreenshotByPathParams struct {
	DirectoryAlias string `json:"directory_alias"`
	Filename       string `json:"filename"`
}

func (q *Queries) GetScreenshotByPath(ctx context.Context, arg GetScreenshotByPathParams) (Screenshot, error) {
	row := q.queryRow(ctx, q.getScreenshotByPathStmt, getScreenshotByPath, arg.DirectoryAlias, arg.Filename)
	var i Screenshot
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.DirectoryAlias,
		&i.Filename,
		&i.DimWidth,
		&i.DimHeight,
		&i.DominantColour,
		&i.Blurhash,
	)
	return i, err
}

const searchBlock = `-- name: SearchBlock :many
select
    id, timestamp, directory_alias, filename, dim_width, dim_height, dominant_colour, blurhash
from
    screenshots
where ($1::text) % body
limit 40
`

func (q *Queries) SearchBlock(ctx context.Context, body string) ([]Screenshot, error) {
	rows, err := q.query(ctx, q.searchBlockStmt, searchBlock, body)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screenshot
	for rows.Next() {
		var i Screenshot
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.DirectoryAlias,
			&i.Filename,
			&i.DimWidth,
			&i.DimHeight,
			&i.DominantColour,
			&i.Blurhash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
