name: dev release
on:
  push:
    branches:
      - master
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v1
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ./backend
          skip-go-installation: true
      - name: Test
        run: go test ./...
        working-directory: ./backend
  build-release:
    name: Build and release Docker image
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login into GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Build Docker image
        run: |
          docker build \
          -t "ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA:0:7}" \
          -t "ghcr.io/${GITHUB_REPOSITORY}:nightly" \
          .
      - name: Release Docker image
        run: |
          docker push "ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA:0:7}"
          docker push "ghcr.io/${GITHUB_REPOSITORY}:nightly"
