name: Lint and test
on:
  push:
    branches:
      - develop
  pull_request:
jobs:
  test-frontend:
    name: Lint and test frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
        working-directory: web
      - name: Check types
        run: npm run check-types
        working-directory: web
      - name: Check formatting
        run: npm run check-formatting
        working-directory: web
  test-backend:
    name: Lint and test backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y -qq build-essential libtesseract-dev libleptonica-dev libavcodec-dev libavutil-dev libavformat-dev libswscale-dev libgraphicsmagick1-dev
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.49.0
          skip-go-installation: true
      - name: Test
        run: go test ./...
